<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DurasiSewa_2hari</name>
   <tag></tag>
   <elementGuidId>95ddbc57-69ef-44b0-ae76-d897906b61ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[6]/div/div[2]/div/div/div[4]/div[3]/div/div[2]/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>afba47f5-e2b2-4816-9969-bd1327d52779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b5410549-69ae-4780-a678-9db24e96405e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1dbjc4n r-1vo5lcr r-qklmqi r-1loqt21 r-1qhn6m8 r-5njf8e r-1otgn73 r-1i6wzkk r-lrvibr</value>
      <webElementGuid>a9de9f91-da88-4c6c-8387-a8f5b7f801af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 hariTanggal Selesai Rental: Rab, 8 Feb 2023</value>
      <webElementGuid>10b47f00-e07d-4771-9476-567a06fb5785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-b4qz5r r-bztko3 r-nsbfu8 r-uwe93p&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1h0z5md&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-1wh2hl7 r-e65k4z r-b4qz5r r-1udh08x r-u8s1d&quot;]/div[@class=&quot;css-1dbjc4n r-150rngu r-eqz5dr r-16y2uox r-1wbh5a2 r-11yh6sk r-1rnoaur r-1sncvnh&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1vo5lcr r-qklmqi r-1loqt21 r-1qhn6m8 r-5njf8e r-1otgn73 r-1i6wzkk r-lrvibr&quot;]</value>
      <webElementGuid>4dc10fb6-6747-4d81-b344-718d59217a65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[6]/div/div[2]/div/div/div[4]/div[3]/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>df0ba344-c591-4aa2-a5b2-429f3b1a3f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Selesai Rental: Sel, 7 Feb 2023'])[1]/following::div[1]</value>
      <webElementGuid>b0ae2ff9-658f-4b85-99cc-ccb732516689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Durasi'])[1]/following::div[11]</value>
      <webElementGuid>f25f797b-ab46-4f94-b722-157b7c5601c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Selesai Rental: Kam, 9 Feb 2023'])[1]/preceding::div[4]</value>
      <webElementGuid>a80bced3-fa21-48cf-b900-36f327129c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>eb4598d7-24e5-433b-907a-5a1a144e0909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2 hariTanggal Selesai Rental: Rab, 8 Feb 2023' or . = '2 hariTanggal Selesai Rental: Rab, 8 Feb 2023')]</value>
      <webElementGuid>020f2602-ebd0-4725-b382-029f3eec0bee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
